replicaCount: 1

image:
  repository: devagent
  tag: latest
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 80

ingress:
  enabled: true
  className: "nginx"
  annotations:
    kubernetes.io/ingress.class: nginx
  hosts:
    - host: devagent.local
      paths:
        - path: /
          pathType: Prefix

resources:
  requests:
    cpu: 100m
    memory: 128Mi
  limits:
    cpu: 200m
    memory: 256Mi

env:
  DATABASE_URL: "postgresql://postgres:postgres@postgres:5432/devagent"
  REDIS_URL: "redis://redis:6379/0"
  JWT_SECRET: "dev-secret-key"
  PROMETHEUS_URL: "http://prometheus:9090"
  GRAFANA_URL: "http://grafana:3000"
  ALERT_WEBHOOK_URL: "http://alertmanager:9093/api/v1/alerts"
  SMTP_HOST: "smtp.gmail.com"
  SMTP_PORT: "587"
  SMTP_USER: "test@example.com"
  SMTP_PASSWORD: "test-password"
  SLACK_WEBHOOK_URL: "https://hooks.slack.com/services/test"
  TEAMS_WEBHOOK_URL: "https://outlook.office.com/webhook/test"

livenessProbe:
  enabled: true
  path: /health
  initialDelaySeconds: 30
  periodSeconds: 10

readinessProbe:
  enabled: true
  path: /ready
  initialDelaySeconds: 5
  periodSeconds: 5

nodeSelector: {}
tolerations: []
affinity: {} 