replicaCount: 3

image:
  repository: southamerica-west1-docker.pkg.dev/YOUR_PROJECT_ID/devagent/devagent
  tag: latest
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 80

ingress:
  enabled: true
  className: "nginx"
  annotations:
    kubernetes.io/ingress.class: nginx
    cert-manager.io/cluster-issuer: letsencrypt-prod
  hosts:
    - host: devagent.example.com
      paths:
        - path: /
          pathType: Prefix
  tls:
    - secretName: devagent-tls
      hosts:
        - devagent.example.com

resources:
  requests:
    cpu: 100m
    memory: 256Mi
  limits:
    cpu: 500m
    memory: 512Mi

env:
  DATABASE_URL: "postgresql://postgres:password@127.0.0.1:5432/devagent"
  REDIS_URL: "redis://127.0.0.1:6379/0"
  JWT_SECRET: "your-secret-key"
  PROMETHEUS_URL: "http://prometheus:9090"
  GRAFANA_URL: "http://grafana:3000"
  ALERT_WEBHOOK_URL: "http://alertmanager:9093/api/v1/alerts"
  SMTP_HOST: "smtp.gmail.com"
  SMTP_PORT: "587"
  SMTP_USER: "your-email@gmail.com"
  SMTP_PASSWORD: "your-app-password"
  SLACK_WEBHOOK_URL: "https://hooks.slack.com/services/your-webhook-url"
  TEAMS_WEBHOOK_URL: "https://outlook.office.com/webhook/your-webhook-url"

livenessProbe:
  enabled: true
  path: /health
  initialDelaySeconds: 30
  periodSeconds: 10

readinessProbe:
  enabled: true
  path: /ready
  initialDelaySeconds: 5
  periodSeconds: 5

nodeSelector: {}
tolerations: []
affinity: {} 