global:
  resolve_timeout: 5m

route:
  group_by: ['alertname', 'job']
  group_wait: 30s
  group_interval: 5m
  repeat_interval: 12h
  receiver: 'team-notifications'

receivers:
  - name: 'team-notifications'
    # The actual webhook URLs will be configured by the team
    webhook_configs:
      - url: 'http://localhost:8080'
        send_resolved: true

templates:
  - '/etc/alertmanager/templates/*.tmpl' 