{{- $serviceName := printf "%s-%s-%s" .Release.Name .Chart.Name "ui" | trunc 63 | trimSuffix "-" -}}
{{- $podSelectorName := printf "%s-%s" .Chart.Name "ui" | trunc 63 | trimSuffix "-" -}}
{{- $backendConfigName := printf "%s-backendconfig" $serviceName -}}
apiVersion: cloud.google.com/v1
kind: BackendConfig
metadata:
  name: {{ $backendConfigName }}
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: {{ $serviceName }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    helm.sh/chart: {{ printf "%s-%s" .Chart.Name .Chart.Version | replace "+" "_" }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  healthCheck:
    checkIntervalSec: 15
    healthyThreshold: 1
    port: 80
    requestPath: /
    timeoutSec: 15
    type: HTTP
    unhealthyThreshold: 2
