{{- $componentName := "ui" -}}
{{- $fullname := printf "%s-%s-%s" .Release.Name .Chart.Name $componentName | trunc 63 | trimSuffix "-" -}}
{{- $backendConfigName := printf "%s-backendconfig" $fullname -}}
apiVersion: cloud.google.com/v1
kind: BackendConfig
metadata:
  name: {{ $backendConfigName }}
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: {{ $fullname }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    helm.sh/chart: {{ printf "%s-%s" .Chart.Name .Chart.Version | replace "+" "_" }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  healthCheck:
    checkIntervalSec: 15
    timeoutSec: 15
    healthyThreshold: 1
    unhealthyThreshold: 2
    type: HTTP
    requestPath: /en/
    port: 3000 # This should be the container targetPort for the UI 