{{- $serviceName := printf "%s-%s-%s" .Release.Name .Chart.Name "ui" | trunc 63 | trimSuffix "-" -}}
{{- $podSelectorName := printf "%s-%s" .Chart.Name "ui" | trunc 63 | trimSuffix "-" -}}
{{- $backendConfigName := printf "%s-backendconfig" $serviceName -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ $serviceName }}
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: {{ $serviceName }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    helm.sh/chart: {{ printf "%s-%s" .Chart.Name .Chart.Version | replace "+" "_" }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
  annotations:
    cloud.google.com/neg: '{"ingress": true}'
    cloud.google.com/backend-config: '{"ports": {"{{ .Values.service.port }}":"{{ $backendConfigName }}"}}'
    {{- with .Values.service.annotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: {{ $podSelectorName }}
    app.kubernetes.io/instance: {{ .Release.Name }} 