{{- $componentName := "ui" -}}
{{- $fullname := printf "%s-%s-%s" .Release.Name .Chart.Name $componentName | trunc 63 | trimSuffix "-" -}}
{{- $backendConfigName := printf "%s-backendconfig" $fullname -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ $fullname }}
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: {{ $fullname }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    helm.sh/chart: {{ printf "%s-%s" .Chart.Name .Chart.Version | replace "+" "_" }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
  annotations:
    cloud.google.com/neg: '{"ingress": true}'
    cloud.google.com/backend-config: '{"ports": {"{{ .Values.service.port }}":"{{ $backendConfigName }}"}}'
    {{- with .Values.service.annotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
      protocol: TCP
      name: http
  selector:
    # This needs to match the actual pod labels set by the deployment template
    # Assuming the deployment uses a similar fullname for its app.kubernetes.io/name selector label
    app.kubernetes.io/name: {{ $fullname }}
    app.kubernetes.io/instance: {{ .Release.Name }} 