apiVersion: cloud.google.com/v1
kind: BackendConfig
metadata:
  name: {{ include "thefullstackagent.fullname" . }}-api-backendconfig
  labels:
    {{- include "thefullstackagent.labels.standard" . | nindent 4 }}
spec:
  healthCheck:
    type: HTTP
    port: {{ .Values.devagentApi.service.port }}
    requestPath: /health
---
apiVersion: cloud.google.com/v1
kind: BackendConfig
metadata:
  name: {{ include "thefullstackagent.fullname" . }}-ui-backendconfig
  labels:
    {{- include "thefullstackagent.labels.standard" . | nindent 4 }}
spec:
  healthCheck:
    type: HTTP
    port: {{ (index .Values "devagent-ui").service.port }}
    requestPath: / 