apiVersion: cloud.google.com/v1
kind: BackendConfig
metadata:
  name: {{ include "agentforge.fullname" . }}-api-backendconfig
  labels:
    {{- include "agentforge.labels.standard" . | nindent 4 }}
spec:
  timeoutSec: 30
---
apiVersion: cloud.google.com/v1
kind: BackendConfig
metadata:
  name: {{ include "agentforge.fullname" . }}-ui-backendconfig
  labels:
    {{- include "agentforge.labels.standard" . | nindent 4 }}
spec:
  timeoutSec: 30
