{{/* Call the common deployment template for the UI component */}}
{{- include "agentforge.component.deployment" (dict
    "Chart" .Chart
    "Release" .Release
    "Values" .Values
    "componentName" "ui"
    "componentValues" .Values.agentforgeUi
  ) | nindent 0 }}
