{{/* Call the common deployment template for the UI component */}}
{{- include "thefullstackagent.component.deployment" (dict 
    "Chart" .Chart 
    "Release" .Release 
    "Values" .Values
    "componentName" "ui" 
    "componentValues" .Values.devagentUi 
  ) | nindent 0 }} 