{{- if .Values.devagentUi.ingress.enabled -}}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ template "thefullstackagent.component.fullname" (dict "Release" .Release "Chart" .Chart "Values" .Values "componentName" "ui") }}
  labels:
    {{- include "thefullstackagent.labels.component" (dict "Release" .Release "Chart" .Chart "Values" .Values "componentName" "ui") | nindent 4 }}
  {{- with .Values.devagentUi.ingress.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  {{- if .Values.devagentUi.ingress.className }}
  ingressClassName: {{ .Values.devagentUi.ingress.className }}
  {{- end }}
  {{- if .Values.devagentUi.ingress.tls }}
  tls:
    {{- range .Values.devagentUi.ingress.tls }}
    - hosts:
        {{- range .hosts }}
        - {{ . | quote }}
        {{- end }}
      secretName: {{ .secretName }}
    {{- end }}
  {{- end }}
  rules:
    {{- range .Values.devagentUi.ingress.hosts }}
    - host: {{ .host | quote }}
      http:
        paths:
          {{- range .paths }}
          - path: {{ .path }}
            pathType: {{ .pathType }}
            backend:
              service:
                name: {{ .backend.service.name | default (include "thefullstackagent.component.fullname" (dict "Release" $.Release "Chart" $.Chart "Values" $.Values "componentName" "ui")) }}
                port:
                  name: {{ .backend.service.port.name | default "http" }}
          {{- end }}
    {{- end }}
{{- end }} 