{{/* Call the common ingress template for the API component */}}
{{- include "agentforge.component.ingress" (dict
    "Chart" .Chart
    "Release" .Release
    "Values" .Values
    "componentName" "api"
    "componentValues" .Values.agentforgeApi
    "root" .
  ) | nindent 0 }}
