apiVersion: v1
kind: Secret
metadata:
  name: {{ include "thefullstackagent.component.fullname" (dict "Release" .Release "Chart" .Chart "Values" .Values "componentName" "api") }}-secrets
  labels:
    {{- include "thefullstackagent.labels.component" (dict "Release" .Release "Chart" .Chart "Values" .Values "componentName" "api") | nindent 4 }}
type: Opaque
data:
  {{- if .Values.devagentApi.env.JWT_SECRET }}
  JWT_SECRET: {{ .Values.devagentApi.env.JWT_SECRET | b64enc | quote }}
  {{- end }}
  {{- if .Values.devagentApi.env.SMTP_PASSWORD }}
  SMTP_PASSWORD: {{ .Values.devagentApi.env.SMTP_PASSWORD | b64enc | quote }}
  {{- end }}
  # Add other sensitive env vars here that should be in secrets
  # Add more secrets as needed 