{{- if .Values.devagentUi.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "thefullstackagent.component.serviceAccountName" (dict "Release" .Release "Chart" .Chart "Values" .Values "componentName" "ui" "componentValues" .Values.devagentUi) }}
  labels:
    {{- include "thefullstackagent.labels.component" (dict "Release" .Release "Chart" .Chart "Values" .Values "componentName" "ui") | nindent 4 }}
  {{- with .Values.devagentUi.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }} 