{{- if .Values.agentforgeUi.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "agentforge.component.serviceAccountName" (dict "Release" .Release "Chart" .Chart "Values" .Values "componentName" "ui" "componentValues" .Values.agentforgeUi) }}
  labels:
    {{- include "agentforge.labels.component" (dict "Release" .Release "Chart" .Chart "Values" .Values "componentName" "ui") | nindent 4 }}
  {{- with .Values.agentforgeUi.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
