{{/* Call the common service template for the API component */}}
{{- include "agentforge.component.service" (dict
    "Chart" .Chart
    "Release" .Release
    "Values" .Values
    "componentName" "api"
    "componentValues" .Values.agentforgeApi
  ) | nindent 0 }}
