{{/* Call the common service template for the API component */}}
{{- include "thefullstackagent.component.service" (dict 
    "Chart" .Chart 
    "Release" .Release 
    "Values" .Values
    "componentName" "api" 
    "componentValues" .Values.devagentApi 
  ) | nindent 0 }} 