apiVersion: v2
name: agentforge
description: Helm chart for deploying the AgentProvision application suite on Kubernetes
version: 0.1.0
appVersion: "1.0.0"
keywords:
  - devops
  - ai
  - agent
  - iac
  - terraform
  - helm
  - gcp
home: https://github.com/nomade/agentforge
maintainers:
  - name: nomade
    email: your@email.com

dependencies: []
