# GCP specific values for AgentProvisionagent Helm chart

# Disable PostgreSQL subchart (using Cloud SQL)
postgresql:
  enabled: false

# Disable Redis subchart (using Memorystore)
redis:
  enabled: false

agentforgeApi:
  replicaCount: 1
  image:
    repository: gcr.io/aremko-e51ae/agentforge-api
    tag: "latest"
  service:
    type: ClusterIP
    port: 8000
    targetPort: 8000
  db:
    host: "postgres-service-postgresql.default.svc.cluster.local"
    port: 5432
    user: "postgres"
    password: "tTbdm7U6WL"
    name: "postgres"
  env:
    DATABASE_URL: "postgresql://{{ .Values.agentforgeApi.db.user }}:{{ .Values.agentforgeApi.db.password }}@{{ .Values.agentforgeApi.db.host }}:{{ .Values.agentforgeApi.db.port }}/{{ .Values.agentforgeApi.db.name }}"
    REDIS_URL: "redis://{{ .Values.redis.host }}:{{ .Values.redis.port }}"
    ALLOWED_ORIGINS_ENV: "https://agents.datamatic.app, http://agents.datamatic.app"
  ingress:
    enabled: true
    className: "nginx"
    annotations:
      cert-manager.io/cluster-issuer: letsencrypt-prod
    hosts:
      - host: api.agents.datamatic.app
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: agentforge-api
                port:
                  name: http
    tls:
      - secretName: api-agents-datamatic-app-tls
        hosts:
          - api.agents.datamatic.app
  serviceAccount:
    create: true
    name: "gke-deploy-sa"
    annotations:
      iam.gke.io/gcp-service-account: "gke-deploy-sa@aremko-e51ae.iam.gserviceaccount.com"
  nodeSelector: {}
  tolerations: []

fullnameOverride: agentforge

agentforgeUi:
  image:
    repository: gcr.io/aremko-e51ae/agentforge-ui
    tag: "latest"
  replicaCount: 1
  env:
    NEXT_PUBLIC_API_URL: "https://agents.datamatic.app/api/v1"
  ingress:
    enabled: true
    className: "nginx"
    annotations:
      cert-manager.io/cluster-issuer: letsencrypt-prod
    hosts:
      - host: agents.datamatic.app
        paths:
          - path: /
            pathType: ImplementationSpecific
          - path: /api
            pathType: Prefix
            backend:
              service:
                name: agentforge-api
                port:
                  name: http
    tls:
      - secretName: agents-datamatic-app-tls
        hosts:
          - agents.datamatic.app
  serviceAccount:
    create: true
    name: "gke-deploy-sa"
    annotations:
      iam.gke.io/gcp-service-account: "gke-deploy-sa@aremko-e51ae.iam.gserviceaccount.com"

# AgentProvision-ui can be configured similarly if it needs cloud-specific settings
# AgentProvision-ui:
#   enabled: true # Assuming we still want to deploy the UI
#   image:
#     repository: gcr.io/aremko-e51ae/AgentProvision-ui # Ensure this image exists
#     tag: latest
#   # ingress:
#   #   hosts:
#   #     - host: AgentProvision.your-gcp-domain.com # Update with your actual domain
#   #       paths:
#   #         - path: /
#   #           pathType: ImplementationSpecific
#   #   tls:
#   #     - secretName: AgentProvision-ui-tls-gcp
#   #       hosts:
#   #         - AgentProvision.your-gcp-domain.com

redis:
  host: "10.93.221.219"
  port: 6379

# ... existing code ...
