# GCP specific values for thefullstackagent Helm chart

# Disable PostgreSQL subchart (using Cloud SQL)
postgresql:
  enabled: false

# Disable Redis subchart (using Memorystore)
redis:
  enabled: false

devagentApi:
  replicaCount: 1
  image:
    repository: gcr.io/aremko-e51ae/devagent-api
    tag: "latest"
  env:
    DATABASE_URL: "postgresql+asyncpg://{{ .Values.devagentApi.db.user }}:{{ .Values.devagentApi.db.password }}@127.0.0.1:5432/{{ .Values.devagentApi.db.name }}"
    REDIS_URL: "redis://{{ .Values.redis.host }}:{{ .Values.redis.port }}"
  db:
    user: "postgres"
    password: "a-secure-devagent-password" # This should be stored in a secret
    name: "devagent"
  serviceAccount:
    create: true
    name: "gke-deploy-sa"
    annotations:
      iam.gke.io/gcp-service-account: "gke-deploy-sa@aremko-e51ae.iam.gserviceaccount.com"
  sidecars:
    - name: cloud-sql-proxy
      image: "gcr.io/cloud-sql-connectors/cloud-sql-proxy:2.8.0"
      args:
        - "--structured-logs"
        - "--port=5432"
        - "aremko-e51ae:southamerica-west1:devagent-postgres"
      securityContext:
        runAsNonRoot: true
      resources:
        requests:
          memory: "64Mi"
          cpu: "50m"
        limits:
          memory: "128Mi"
          cpu: "100m"
  nodeSelector: {}
  tolerations: []

devagentUi:
  image:
    repository: gcr.io/aremko-e51ae/devagent-ui
    tag: "latest"
  replicaCount: 1
  env:
    NEXT_PUBLIC_API_URL: "https://api.agents.datamatic.app"
  serviceAccount:
    create: true
    name: "gke-deploy-sa"
    annotations:
      iam.gke.io/gcp-service-account: "gke-deploy-sa@aremko-e51ae.iam.gserviceaccount.com"

# devagent-ui can be configured similarly if it needs cloud-specific settings
# devagent-ui:
#   enabled: true # Assuming we still want to deploy the UI
#   image:
#     repository: gcr.io/aremko-e51ae/devagent-ui # Ensure this image exists
#     tag: latest
#   # ingress:
#   #   hosts:
#   #     - host: devagent.your-gcp-domain.com # Update with your actual domain
#   #       paths:
#   #         - path: /
#   #           pathType: ImplementationSpecific
#   #   tls:
#   #     - secretName: devagent-ui-tls-gcp
#   #       hosts:
#   #         - devagent.your-gcp-domain.com 

redis:
  host: "10.93.221.219"
  port: 6379

# ... existing code ... 