# GCP specific values for thefullstackagent Helm chart

# Disable PostgreSQL subchart (using Cloud SQL)
postgresql:
  enabled: false

# Disable Redis subchart (using Memorystore)
redis:
  enabled: false

devagentApi:
  replicaCount: 1 # Ensure API replicas are set to 1
  image:
    repository: gcr.io/aremko-e51ae/devagent-api # Ensure this image exists in your GCR
    tag: latest # Or a specific version/tag
    # pullPolicy: Always # Recommended for GCR to ensure fresh images

  env:
    DATABASE_URL: "postgresql+asyncpg://postgres:replace-with-secure-password@127.0.0.1:5432/devagent"
    REDIS_URL: "redis://10.93.221.219:6379"
    # JWT_SECRET should be a strong, unique secret managed via K8s secrets, not hardcoded here for prod.
    # For now, we'll let it take the default from the main values.yaml or you can override it.
    # JWT_SECRET: "your-gcp-specific-jwt-secret"

  # Configure to use the existing GKE service account created by Terraform
  serviceAccount:
    create: false # Do not create a new service account
    name: gke-deploy-sa # Name of the Terraform-managed Google Service Account (GSA)
                        # This assumes K8s SA with the same name exists or is linked via Workload Identity.
                        # For Cloud SQL Proxy, the POD needs to run with an SA that has cloudsql.client perm.

  resources:
    requests:
      cpu: "75m"
    # Limits will also be inherited (cpu: 500m, memory: 512Mi)

  sidecars:
    - name: cloud-sql-proxy
      image: "gcr.io/cloud-sql-connectors/cloud-sql-proxy:2.8.0" # Use a specific version tag
      # imagePullPolicy: Always # Optional, but good for ensuring latest patch of the version
      args:
        - "--structured-logs"
        - "--port=5432"
        - "aremko-e51ae:southamerica-west1:devagent-postgres"
      securityContext:
        runAsNonRoot: true
      resources:
        requests:
          memory: "64Mi"
          cpu: "50m"
        limits:
          memory: "128Mi"
          cpu: "100m"

  ingress:
    enabled: true
    className: "" # Explicitly empty to use GKE default or annotation
    annotations:
      kubernetes.io/ingress.class: "gce" # Explicitly select GKE Ingress controller
      kubernetes.io/ingress.global-static-ip-name: "devagent-static-ip"
      networking.gke.io/managed-certificates: "devagent-managed-cert"
    hosts:
      - host: "agents.datamatic.app"
        paths:
          - path: /api
            pathType: Prefix
            backend: # Backend for the API
              service:
                name: devagent-thefullstackagent-api # Main API service
                port:
                  name: http
          - path: / # New path for the UI
            pathType: Prefix
            backend: # Backend for the UI
              service:
                name: devagent-devagent-ui-ui # UI service name from subchart
                port:
                  name: http
    tls: [] # TLS is handled by the Google-managed certificate

# Values for the devagent-ui subchart (using its direct name from Chart.yaml dependencies)
"devagent-ui":
  # This enables the subchart itself if it had an enabled flag at its root
  # enabled: true # Assuming this is for the subchart deployment, not ingress specifically.
                # The subchart's own values.yaml has replicaCount > 0 so it's deployed.

  # Configuration for the ingress object within the devagent-ui subchart
  ingress:
    enabled: false # THIS IS THE KEY - Disabling UI subchart's ingress
    # className: ""
    # annotations:
    #   kubernetes.io/ingress.class: "gce"
    #   kubernetes.io/ingress.global-static-ip-name: "devagent-static-ip"
    #   networking.gke.io/managed-certificates: "devagent-managed-cert"
    # hosts:
    #   - host: "agents.datamatic.app"
    #     paths:
    #       - path: /
    #         pathType: Prefix
    # tls: []
  # Other devagent-ui specific overrides if needed, e.g.:
  image:
    repository: gcr.io/aremko-e51ae/devagent-ui
    # tag: latest # REMOVED to ensure CI/CD --set takes precedence
  replicaCount: 1 # Start with 1, can be scaled later
  env:
    NEXT_PUBLIC_API_URL: "/api"

# devagent-ui can be configured similarly if it needs cloud-specific settings
# devagent-ui:
#   enabled: true # Assuming we still want to deploy the UI
#   image:
#     repository: gcr.io/aremko-e51ae/devagent-ui # Ensure this image exists
#     tag: latest
#   # ingress:
#   #   hosts:
#   #     - host: devagent.your-gcp-domain.com # Update with your actual domain
#   #       paths:
#   #         - path: /
#   #           pathType: ImplementationSpecific
#   #   tls:
#   #     - secretName: devagent-ui-tls-gcp
#   #       hosts:
#   #         - devagent.your-gcp-domain.com 