name: Deploy to GKE

on:
  push:
    branches:
      - main # Or your default branch
  workflow_dispatch: # Allows manual triggering
    inputs:
      logLevel: # Example input, not used yet but shows structure
        description: 'Log level'
        required: false
        default: 'warning'

env:
  GCP_PROJECT_ID: aremko-e51ae
  GCP_REGION: southamerica-west1
  GKE_CLUSTER_NAME: devagent-gke
  GCR_HOSTNAME: gcr.io # Or your Artifact Registry hostname e.g. southamerica-west1-docker.pkg.dev
  GAR_REPOSITORY_API: devagent-api # If using GAR, this is the repo name, not part of the image name
  GAR_REPOSITORY_UI: devagent-ui   # If using GAR
  IMAGE_API: devagent-api # This is the image name, not the directory name
  IMAGE_UI: devagent-ui   # This is the image name, not the directory name
  HELM_RELEASE_NAME: devagent
  HELM_NAMESPACE: devagent

permissions:
  contents: 'read'
  id-token: 'write'

jobs:
  build_images:
    name: Build and Push Docker Images
    runs-on: ubuntu-latest
    outputs:
      commit_sha: ${{ steps.set_sha.outputs.sha }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set Commit SHA
        id: set_sha
        run: echo "::set-output name=sha::${{ github.sha }}"

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v1
        with:
          workload_identity_provider: 'projects/828573473542/locations/global/workloadIdentityPools/github-actions-pool/providers/github-actions-provider'
          service_account: 'github-actions-cicd@aremko-e51ae.iam.gserviceaccount.com'

      - name: Login to GCR
        run: gcloud auth configure-docker ${{ env.GCR_HOSTNAME }} --quiet

      - name: Build and push API image
        run: |
          docker build -t ${{ env.GCR_HOSTNAME }}/${{ env.GCP_PROJECT_ID }}/${{ env.IMAGE_API }}:${{ steps.set_sha.outputs.sha }} -f ./devagent/Dockerfile ./devagent
          docker push ${{ env.GCR_HOSTNAME }}/${{ env.GCP_PROJECT_ID }}/${{ env.IMAGE_API }}:${{ steps.set_sha.outputs.sha }}

      - name: Build and push UI image
        run: |
          docker build -t ${{ env.GCR_HOSTNAME }}/${{ env.GCP_PROJECT_ID }}/${{ env.IMAGE_UI }}:${{ steps.set_sha.outputs.sha }} -f ./devagent-ui/Dockerfile ./devagent-ui
          docker push ${{ env.GCR_HOSTNAME }}/${{ env.GCP_PROJECT_ID }}/${{ env.IMAGE_UI }}:${{ steps.set_sha.outputs.sha }}

  deploy_to_gke:
    name: Deploy to GKE
    runs-on: ubuntu-latest
    needs: build_images # Depends on the build_images job
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v1
        with:
          workload_identity_provider: 'projects/828573473542/locations/global/workloadIdentityPools/github-actions-pool/providers/github-actions-provider'
          service_account: 'github-actions-cicd@aremko-e51ae.iam.gserviceaccount.com'

      - name: Set up GKE credentials
        uses: google-github-actions/get-gke-credentials@v1
        with:
          cluster_name: ${{ env.GKE_CLUSTER_NAME }}
          location: ${{ env.GCP_REGION }}
          project_id: ${{ env.GCP_PROJECT_ID }}

      - name: Deploy Helm chart
        run: |
          helm repo add bitnami https://charts.bitnami.com/bitnami
          helm dependency build ./helm/thefullstackagent
          helm upgrade --install ${{ env.HELM_RELEASE_NAME }} ./helm/thefullstackagent \
            --namespace ${{ env.HELM_NAMESPACE }} --create-namespace \
            -f ./helm/thefullstackagent/values-gcp.yaml \
            --set devagentApi.image.repository=${{ env.GCR_HOSTNAME }}/${{ env.GCP_PROJECT_ID }}/${{ env.IMAGE_API }} \
            --set devagent-ui.image.repository=${{ env.GCR_HOSTNAME }}/${{ env.GCP_PROJECT_ID }}/${{ env.IMAGE_UI }} \
            --set devagentApi.image.tag=${{ needs.build_images.outputs.commit_sha }} \
            --set devagent-ui.image.tag=${{ needs.build_images.outputs.commit_sha }} 