name: Deploy to GKE

on:
  push:
    branches:
      - main
  workflow_dispatch:

env:
  GCP_PROJECT_ID: aremko-e51ae
  GCP_REGION: southamerica-west1
  GKE_CLUSTER_NAME: AgentProvision-gke
  GCR_HOSTNAME: gcr.io
  IMAGE_API: AgentProvision-api
  IMAGE_UI: AgentProvision-ui
  HELM_RELEASE_NAME: AgentProvision
  HELM_NAMESPACE: AgentProvision

permissions:
  contents: 'read'
  id-token: 'write'

jobs:
  build_and_deploy:
    name: Build and Deploy to GKE
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Get Commit SHA
        id: get_sha
        run: echo "sha=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v1
        with:
          workload_identity_provider: 'projects/828573473542/locations/global/workloadIdentityPools/github-actions-pool/providers/github-actions-provider'
          service_account: 'github-actions-cicd@aremko-e51ae.iam.gserviceaccount.com'

      - name: Login to GCR
        run: gcloud auth configure-docker ${{ env.GCR_HOSTNAME }} --quiet

      - name: Build and push API image
        run: |
          docker build --no-cache -t ${{ env.GCR_HOSTNAME }}/${{ env.GCP_PROJECT_ID }}/${{ env.IMAGE_API }}:${{ steps.get_sha.outputs.sha }} -f ./AgentProvision/Dockerfile ./AgentProvision
          docker push ${{ env.GCR_HOSTNAME }}/${{ env.GCP_PROJECT_ID }}/${{ env.IMAGE_API }}:${{ steps.get_sha.outputs.sha }}

      - name: Build and push UI image
        run: |
          docker build --build-arg NEXT_PUBLIC_API_URL=https://agents.datamatic.app/api/v1 -t ${{ env.GCR_HOSTNAME }}/${{ env.GCP_PROJECT_ID }}/${{ env.IMAGE_UI }}:${{ steps.get_sha.outputs.sha }} -f ./AgentProvision-ui/Dockerfile ./AgentProvision-ui
          docker push ${{ env.GCR_HOSTNAME }}/${{ env.GCP_PROJECT_ID }}/${{ env.IMAGE_UI }}:${{ steps.get_sha.outputs.sha }}

      - name: Set up GKE credentials
        uses: google-github-actions/get-gke-credentials@v1
        with:
          cluster_name: ${{ env.GKE_CLUSTER_NAME }}
          location: ${{ env.GCP_REGION }}
          project_id: ${{ env.GCP_PROJECT_ID }}

      - name: Deploy to GKE
        run: |
          helm repo add bitnami https://charts.bitnami.com/bitnami
          helm dependency update ./helm/AgentProvisionagent

          # Add deletion commands here
          kubectl delete ingress AgentProvisionagent-api -n dev-agent --ignore-not-found
          kubectl delete ingress AgentProvisionagent-ui -n dev-agent --ignore-not-found

          helm upgrade --install AgentProvision ./helm/AgentProvisionagent \
            --namespace dev-agent \
            --create-namespace \
            --values ./helm/AgentProvisionagent/values-gcp.yaml \
            --set AgentProvisionApi.image.tag=${{ steps.get_sha.outputs.sha }} \
            --set AgentProvisionUi.image.tag=${{ steps.get_sha.outputs.sha }}
