name: Deploy to GKE

on:
  push:
    branches:
      - main # Or your default branch

env:
  GCP_PROJECT_ID: aremko-e51ae
  GCP_REGION: southamerica-west1
  GKE_CLUSTER_NAME: devagent-gke
  GCR_HOSTNAME: gcr.io # Or your Artifact Registry hostname e.g. southamerica-west1-docker.pkg.dev
  GAR_REPOSITORY_API: devagent-api # If using GAR, this is the repo name, not part of the image name
  GAR_REPOSITORY_UI: devagent-ui   # If using GAR
  IMAGE_API: devagent-api
  IMAGE_UI: devagent-ui
  HELM_RELEASE_NAME: devagent
  HELM_NAMESPACE: devagent

permissions:
  contents: 'read'
  id-token: 'write'

jobs:
  deploy:
    name: Build and Deploy
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v1
        with:
          workload_identity_provider: 'projects/828573473542/locations/global/workloadIdentityPools/github-actions-pool/providers/github-actions-provider'
          service_account: 'github-actions-cicd@aremko-e51ae.iam.gserviceaccount.com'

      - name: Set up GKE credentials
        uses: google-github-actions/get-gke-credentials@v1
        with:
          cluster_name: ${{ env.GKE_CLUSTER_NAME }}
          location: ${{ env.GCP_REGION }}
          project_id: ${{ env.GCP_PROJECT_ID }}

      # Docker Build & Push Steps (Placeholder - to be implemented if needed)
      # - name: Login to GCR
      #   uses: docker/login-action@v2
      #   with:
      #     registry: ${{ env.GCR_HOSTNAME }}
      #     username: oauth2accesstoken
      #     password: ${{ steps.auth.outputs.access_token }} # Assuming auth step outputs access_token

      # - name: Build and push API image
      #   run: |-
      #     docker build -t ${{ env.GCR_HOSTNAME }}/${{ env.GCP_PROJECT_ID }}/${{ env.IMAGE_API }}:latest ./devagent-api
      #     docker push ${{ env.GCR_HOSTNAME }}/${{ env.GCP_PROJECT_ID }}/${{ env.IMAGE_API }}:latest
      #   working-directory: ${{ github.workspace }} # Adjust if Dockerfile is elsewhere

      # - name: Build and push UI image
      #   run: |-
      #     docker build -t ${{ env.GCR_HOSTNAME }}/${{ env.GCP_PROJECT_ID }}/${{ env.IMAGE_UI }}:latest ./devagent-ui
      #     docker push ${{ env.GCR_HOSTNAME }}/${{ env.GCP_PROJECT_ID }}/${{ env.IMAGE_UI }}:latest
      #   working-directory: ${{ github.workspace }} # Adjust if Dockerfile is elsewhere

      - name: Deploy Helm chart
        run: |-
          helm upgrade --install ${{ env.HELM_RELEASE_NAME }} ./helm/thefullstackagent \
            --namespace ${{ env.HELM_NAMESPACE }} \
            --create-namespace \
            -f ./helm/thefullstackagent/values-gcp.yaml \
            --set devagentApi.image.repository=${{ env.GCR_HOSTNAME }}/${{ env.GCP_PROJECT_ID }}/${{ env.IMAGE_API }} \
            --set devagentUi.image.repository=${{ env.GCR_HOSTNAME }}/${{ env.GCP_PROJECT_ID }}/${{ env.IMAGE_UI }} \
            --set devagentApi.image.tag=latest \
            --set devagentUi.image.tag=latest 